server:
  port: 8989
spring:
  http:
    encoding:
      charset: UTF-8
  datasource:
#    url: jdbc:mysql://10.5.151.19:3306/myReptile?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    url: jdbc:mysql://8.130.72.20:3306/myReptile?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: dong.123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:   # 防止一段时间自动断连
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

  # redis 配置
#  redis:
#    # 地址
#    host: 103.152.132.184
##    host: 10.5.151.19
#    # 端口，默认为6379
#    port: 6379
#    # 密码
#    password: 123456
#    # 连接超时时间
#    timeout: 10s
#    lettuce:
#      pool:
#        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
#        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
#        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
#        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER